<?php

namespace App\Filament\Resources\TeacherResource\Pages;

use App\Filament\Resources\TeacherResource;
use App\Models\Family;
use App\Models\User;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Contracts\Support\Htmlable;

class CreateTeacher extends CreateRecord
{
    protected static string $resource = TeacherResource::class;
    public function getTitle(): string|Htmlable
    {
        if($family_id = request('family_id')){ //Estoy mostrando profesores de una familia
            $family = Family::find($family_id);
            $count = User::role("teacher")->whereHas('specialization', fn ($q) => $q->where('family_id', $family_id))->count();
            return ($count ." ". __("Crear teacher de ").$family->name);
        }
        return parent::getTitle(); // TODO: Change the autogenerated stub
    }
}

