<?php


return [
    "Informática y Comunicaciones" => [
        ["SMR", "Sistemas Microinformáticos y Redes"],
        ["ASIR", "Administración de Sistemas Informáticos en Red"],
        ["DAM", "Desarrollo de Aplicaciones Multiplataforma"],
        ["DAW", "Desarrollo de Aplicaciones Web"],
    ],
    "Comercio y Marketing" => [
        ["COM", "Actividades Comerciales"],
        ["INT", "Comercio Internacional"],
        ["MKP", "Marketing y Publicidad"],
        ["GVEC", "Gestión de Ventas y Espacios Comerciales"],
        ["TRLO", "Transporte y Logística"],
    ],
    "Sanidad" => [
        ["CAU", "Cuidados Auxiliares de Enfermería"],
        ["FAR", "Farmacia y Parafarmacia"],
        ["HBD", "Higiene Bucodental"],
        ["LAB", "Laboratorio Clínico y Biomédico"],
        ["RAD", "Imagen para el Diagnóstico y Medicina Nuclear"],
        ["DIE", "Dietética"],
        ["DOC", "Documentación y Administración Sanitarias"],
        ["PRD", "Prótesis Dentales"],
        ["ORT", "Ortoprótesis y Productos de Apoyo"],
        ["AUD", "Audiología Protésica"],
        ["RDT", "Radioterapia y Dosimetría"],
    ],
    "Administración y Gestión" => [
        ["GAD", "Gestión Administrativa"],
        ["AFI", "Administración y Finanzas"],
        ["AAD", "Asistencia a la Dirección"],
    ],
    "Electricidad y Electrónica" => [
        ["IEA", "Instalaciones Eléctricas y Automáticas"],
        ["AUT", "Automatización y Robótica Industrial"],
        ["MEL", "Mantenimiento Electrónico"],
        ["SIA", "Sistemas Electrotécnicos y Automatizados"],
        ["STEI", "Sistemas de Telecomunicaciones e Informáticos"],
        ["EMC", "Electromedicina Clínica"],
    ],
    "Servicios Socioculturales y a la Comunidad" => [
        ["EDIN", "Educación Infantil"],
        ["INS", "Integración Social"],
        ["MED", "Mediación Comunicativa"],
        ["AIS", "Animación Sociocultural y Turística"],
        ["PIG", "Promoción de Igualdad de Género"],
        ["FMS", "Formación para la Movilidad Segura y Sostenible"],
    ],
    "Hostelería y Turismo" => [
        ["COG", "Cocina y Gastronomía"],
        ["SRR", "Servicios en Restauración"],
        ["DCO", "Dirección de Cocina"],
        ["DSR", "Dirección de Servicios de Restauración"],
        ["GAT", "Gestión de Alojamientos Turísticos"],
        ["GIA", "Guía, Información y Asistencias Turísticas"],
        ["AGE", "Agencias de Viajes y Gestión de Eventos"],
    ],
    "Imagen y Sonido" => [
        ["VDS", "Vídeo Disc-jockey y Sonido"],
        ["ANI", "Animaciones 3D, Juegos y Entornos Interactivos"],
        ["ILU", "Iluminación, Captación y Tratamiento de Imagen"],
        ["PRO", "Producción de Audiovisuales y Espectáculos"],
        ["REA", "Realización de Proyectos Audiovisuales y Espectáculos"],
        ["SAV", "Sonido para Audiovisuales y Espectáculos"],
    ],
    "Fabricación Mecánica" => [
        ["MEC", "Mecanizado"],
        ["SYC", "Soldadura y Calderería"],
        ["CFM", "Conformado por Moldeo de Metales y Polímeros"],
        ["DFA", "Diseño en Fabricación Mecánica"],
        ["PPF", "Programación de la Producción en Fabricación Mecánica"],
        ["PPM", "Programación de la Producción en Moldeo de Metales y Polímeros"],
        ["CM", "Construcciones Metálicas"],
        ["OPT", "Óptica de Anteojería"],
    ],
    "Química" => [
        ["OPL", "Operaciones de Laboratorio"],
        ["PQU", "Planta Química"],
        ["FPB", "Fabricación de Productos Farmacéuticos, Biotecnológicos y Afines"],
        ["LAC", "Laboratorio de Análisis y de Control de Calidad"],
        ["QUI", "Química Industrial"],
    ],
    "Transporte y Mantenimiento de Vehículos" => [
        ["MAV", "Mantenimiento de Vehículos"],
        ["AUT", "Automoción"],
        ["MAVP", "Mantenimiento Aeromecánico de Aviones con Motor de Pistón"],
        ["MAVT", "Mantenimiento Aeromecánico de Aviones con Motor de Turbina"],
        ["MAHP", "Mantenimiento Aeromecánico de Helicópteros con Motor de Pistón"],
        ["MAHT", "Mantenimiento Aeromecánico de Helicópteros con Motor de Turbina"],
        ["MSEA", "Mantenimiento de Sistemas Electrónicos y Aviónicos de Aeronaves"],
    ],
];
