<?php

namespace App\Filament\Pages;

use Filament\Pages\Page;
use App\Models\User;
use App\Models\Project;


class Dashboard extends Page
{
    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.pages.dashboard';

    protected function getHeaderWidgets(): array
    {
        return [

            \App\Filament\Widgets\ProjectStats::class
        ];
    }
//    public function getLayout(): string{
//        return "layouts.filament.";
//    }
    public function getViewData(): array
    {
        return [
            'teachersCount' => User::role('teacher')->count(),
            'projectsCount' => Project::count(),
            'queriesCount' => 0, // Replace with your own logic
        ];
//        return parent::getViewData(); // TODO: Change the autogenerated stub
    }
}
